[versions]
junit = "5.9.3"

[plugins]
pluginProject = { id = "com.cthing.gradle-plugin-project", version = "0.2.0-+"}
dependencyAnalysis = { id = "com.cthing.dependency-analysis", version = "0.2.0-+"}

[libraries]
assertJ = "org.assertj:assertj-core:3.24.2"
corePlugins = "com.cthing:gradle-core:0.2.0-+"
cthingJasypt = "com.cthing:cthing-jasypt:0.2.0-+"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = "org.junit.platform:junit-platform-launcher:1.9.3"
